### ISSUE TITLE
Invalid discord link

### ISSUE THREAD

**Issue by SylisMC** [jtorleonstudios/HUB-Awesome-Dungeon#11]
The discord link "discord.com/invite/pvb4XfYg94" provided at [Github](https://jtorleonstudios.github.io/JTorleonStudios/awesome_dungeon.html) has expired

**Comment by McKitten** [comment]
Seconded. "jtorleonstudios.github.io" page has an expired invite.
I went looking for info about the config. 
I don't do twits, Both Reddit's seem discontinued and I see here I am not the first to discover the discord link invalid.

**Comment by jtorleonstudios** [comment]
The configuration has been implemented in the new version, a rewrite of the code was necessary for the version above 1.18.2

The discord is closed

sorry for the delay of our answer, thanks you for your feedback.
