### ISSUE TITLE
Structures overlapping

### ISSUE THREAD

**Issue by AlphaKaos** [jtorleonstudios/HUB-Awesome-Dungeon#15]
MC Version: 1.16.5
Forge Version: 36.2.39
Mod Version: 1.16.5-3.1.0

Whenever a world is loaded up, dungeons are overlapping over each other. Specifically the ones provided in the picture below.

![image](https://user-images.githubusercontent.com/130933040/232340381-6faa5e08-e0b3-42e3-97ba-ac5168e84405.png)

**Comment by jtorleonstudios** [comment]
Fixed in 3.2.0 (soon available in curseforge)

Thanks you for you feedback.
