### ISSUE TITLE
Update for Minecraft 1.20.x on Fabric

### ISSUE THREAD

**Issue by lospejos** [jtorleonstudios/HUB-Awesome-Dungeon#18]
Please update for Minecraft 1.20.x on Fabric. Thanks!

**Comment by jtorleonstudios** [comment]
Yes of course, it's in progress.

Thanks you for your patience

**Comment by OBS3SS1ON** [comment]
> Yes of course, it's in progress.
> 
> Thanks you for your patience

Hi!! how much is left for the 1.20.1 forge thx!!

**Comment by jtorleonstudios** [comment]
in the next days, is in progress maybe today

**Comment by jtorleonstudios** [comment]
1.20.1 released
