### ISSUE TITLE
Using your mods in my modpack on modrinth

### ISSUE THREAD

**Issue by SpiritOTHawk** [jtorleonstudios/HUB-Awesome-Dungeon#19]
Hi! Can i use your mods (awesomedungeon, awesomedungeonocean, awesomedungeonnether) in my modpack on modrinth?

**Comment by jtorleonstudios** [comment]
Hi, Only on curseforge

**Comment by jtorleonstudios** [comment]
Because the license is All Right Reserved, and our content is only published on Curseforge.
